In [1]:
import pandas as pd

In [2]:
freshers = pd.read_csv("D:\\c drive 16.07.26\\Desktop\\Postgresql\\fresher_hiring_india_dataset.csv")
print(freshers)

      candidate_id       full_name  gender  age  graduation_year  \
0                1  Deepika Shukla  Female   23             2021
1                2    Piyush Reddy    Male   25             2022
2                3    Itisha Arora  Female   21             2024
3                4     Darshan Dey    Male   22             2022
4                5      Uma Grewal  Female   25             2020
...            ...             ...     ...  ...              ...
4995          4996    Bhumi Shukla  Female   20             2021
4996          4997    Hemant Rajan    Male   24             2023
4997          4998     Ojaswi More  Female   21             2020
4998          4999    Ojaswi Kumar  Female   23             2021
4999          5000   Shivam Sharma    Male   25             2020

                           college     degree                  branch  cgpa  \
0                         BITS Goa       B.E.              Electrical  5.89
1                    IIEST Shibpur  B.Sc (IT)  Information Technology  8.78
2                 BIT Mesra Ranchi        BCA   Computer Applications  6.24
3                         BITS Goa  B.Sc (CS)        Computer Science  8.86
4                  Pune University        MCA   Computer Applications  7.54
...                            ...        ...                     ...   ...
4995                  IIM Calcutta  B.Sc (CS)        Computer Science  7.94
4996  Osmania University Hyderabad     B.Tech        Computer Science  5.56
4997                   NIT Calicut        BBA               Marketing  9.71
4998               Pune University     M.Tech                    VLSI  6.84
4999   Jadavpur University Kolkata        MBA              Operations  7.20

      backlogs  ...   job_location application_date         hiring_stage  \
0            3  ...      Bengaluru       11/23/2021  Technical Interview
1            0  ...      Ahmedabad        7/26/2021          Shortlisted
2            3  ...      Delhi NCR         3/9/2022             Rejected
3            3  ...     Coimbatore        8/17/2023    Online Assessment
4            2  ...      Bengaluru        5/11/2024          Shortlisted
...        ...  ...            ...              ...                  ...
4995         1  ...  Visakhapatnam       10/15/2023  Technical Interview
4996         2  ...      Bengaluru        4/16/2021  Technical Interview
4997         1  ...         Nagpur        4/10/2023              Applied
4998         1  ...         Bhopal        1/19/2024              Applied
4999         0  ...         Mumbai        3/27/2022  Technical Interview

      interview_rounds response_time_days offered_salary_inr  \
0                  3.0                 22                NaN
1                  NaN                 30                NaN
2                  4.0                 37                NaN
3                  NaN                 36                NaN
4                  NaN                  2                NaN
...                ...                ...                ...
4995               5.0                 40                NaN
4996               5.0                  5                NaN
4997               NaN                 12                NaN
4998               NaN                 21                NaN
4999               3.0                 14                NaN

     linkedin_connections profile_completion_pct linkedin_premium  \
0                    1188                     64              NaN
1                    2653                     78              Yes
2                    2990                     75              NaN
3                      97                     98               No
4                     508                     78               No
...                   ...                    ...              ...
4995                 1392                     84              NaN
4996                 1401                     70              Yes
4997                 1159                     66              NaN
4998                  399                     84              NaN
4999                 2586                     87              NaN

     referral_applied
0                  No
1                  No
2                  No
3                  No
4                  No
...               ...
4995              Yes
4996               No
4997               No
4998              Yes
4999              Yes

[5000 rows x 30 columns]

In [3]:
# To see the first 5 rows of the table
freshers.head(5)

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,job_location,application_date,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Bengaluru,11/23/2021,Technical Interview,3.0,22,NaN,1188,64,NaN,No
1,2,Piyush Reddy,Male,25,2022,IIEST Shibpur,B.Sc (IT),Information Technology,8.78,0,...,Ahmedabad,7/26/2021,Shortlisted,NaN,30,NaN,2653,78,Yes,No
2,3,Itisha Arora,Female,21,2024,BIT Mesra Ranchi,BCA,Computer Applications,6.24,3,...,Delhi NCR,3/9/2022,Rejected,4.0,37,NaN,2990,75,NaN,No
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Coimbatore,8/17/2023,Online Assessment,NaN,36,NaN,97,98,No,No
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Bengaluru,5/11/2024,Shortlisted,NaN,2,NaN,508,78,No,No

In [4]:
# To see the last 5 rows of the table
freshers.tail(5)

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,job_location,application_date,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied
4995,4996,Bhumi Shukla,Female,20,2021,IIM Calcutta,B.Sc (CS),Computer Science,7.94,1,...,Visakhapatnam,10/15/2023,Technical Interview,5.0,40,NaN,1392,84,NaN,Yes
4996,4997,Hemant Rajan,Male,24,2023,Osmania University Hyderabad,B.Tech,Computer Science,5.56,2,...,Bengaluru,4/16/2021,Technical Interview,5.0,5,NaN,1401,70,Yes,No
4997,4998,Ojaswi More,Female,21,2020,NIT Calicut,BBA,Marketing,9.71,1,...,Nagpur,4/10/2023,Applied,NaN,12,NaN,1159,66,NaN,No
4998,4999,Ojaswi Kumar,Female,23,2021,Pune University,M.Tech,VLSI,6.84,1,...,Bhopal,1/19/2024,Applied,NaN,21,NaN,399,84,NaN,Yes
4999,5000,Shivam Sharma,Male,25,2020,Jadavpur University Kolkata,MBA,Operations,7.20,0,...,Mumbai,3/27/2022,Technical Interview,3.0,14,NaN,2586,87,NaN,Yes

In [5]:
freshers.describe()

,candidate_id,age,graduation_year,cgpa,backlogs,projects_count,certifications_count,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,1818.000000,5000.000000,6.220000e+02,5000.000000,5000.000000
mean,2500.500000,23.501800,2022.491000,7.742102,1.500200,2.998000,2.49780,3.036304,23.244600,4.916031e+05,1522.969200,77.446600
std,1443.520003,2.293262,1.705785,1.304093,1.119397,1.999699,1.70299,1.412189,13.013418,3.911957e+05,854.079153,13.177567
min,1.000000,20.000000,2020.000000,5.500000,0.000000,0.000000,0.00000,1.000000,1.000000,8.098000e+03,50.000000,55.000000
25%,1250.750000,21.000000,2021.000000,6.620000,0.000000,1.000000,1.00000,2.000000,12.000000,3.646150e+04,782.750000,66.000000
50%,2500.500000,24.000000,2022.000000,7.730000,1.000000,3.000000,2.00000,3.000000,24.000000,4.900845e+05,1515.000000,78.000000
75%,3750.250000,26.000000,2024.000000,8.890000,3.000000,5.000000,4.00000,4.000000,35.000000,7.295302e+05,2276.000000,89.000000
max,5000.000000,27.000000,2025.000000,10.000000,3.000000,6.000000,5.00000,5.000000,45.000000,1.925970e+06,3000.000000,100.000000

In [6]:
freshers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   candidate_id            5000 non-null   int64
 1   full_name               5000 non-null   object
 2   gender                  5000 non-null   object
 3   age                     5000 non-null   int64
 4   graduation_year         5000 non-null   int64
 5   college                 5000 non-null   object
 6   degree                  5000 non-null   object
 7   branch                  5000 non-null   object
 8   cgpa                    5000 non-null   float64
 9   backlogs                5000 non-null   int64
 10  gap_year                5000 non-null   object
 11  prior_internship        5000 non-null   object
 12  projects_count          5000 non-null   int64
 13  certifications_count    5000 non-null   int64
 14  top_skills              5000 non-null   object
 15  platform                5000 non-null   object
 16  company_applied         5000 non-null   object
 17  sector                  5000 non-null   object
 18  job_role                5000 non-null   object
 19  work_type               5000 non-null   object
 20  job_location            5000 non-null   object
 21  application_date        5000 non-null   object
 22  hiring_stage            5000 non-null   object
 23  interview_rounds        1818 non-null   float64
 24  response_time_days      5000 non-null   int64
 25  offered_salary_inr      622 non-null    float64
 26  linkedin_connections    5000 non-null   int64
 27  profile_completion_pct  5000 non-null   int64
 28  linkedin_premium        1099 non-null   object
 29  referral_applied        5000 non-null   object
dtypes: float64(3), int64(9), object(18)
memory usage: 1.1+ MB

In [7]:
# To see all the column names
freshers.columns

Index(['candidate_id', 'full_name', 'gender', 'age', 'graduation_year',
       'college', 'degree', 'branch', 'cgpa', 'backlogs', 'gap_year',
       'prior_internship', 'projects_count', 'certifications_count',
       'top_skills', 'platform', 'company_applied', 'sector', 'job_role',
       'work_type', 'job_location', 'application_date', 'hiring_stage',
       'interview_rounds', 'response_time_days', 'offered_salary_inr',
       'linkedin_connections', 'profile_completion_pct', 'linkedin_premium',
       'referral_applied'],
      dtype='object')

In [8]:
# To check the numbers of rows in the table
len(freshers)

5000

In [9]:
freshers.shape

(5000, 30)

In [10]:
# To see particular rows
freshers.iloc[5:10]

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,job_location,application_date,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Mysuru,8/23/2024,Shortlisted,NaN,34,NaN,1899,62,NaN,No
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Visakhapatnam,3/26/2024,Online Assessment,NaN,31,NaN,1717,67,NaN,Yes
7,8,Hema Sengupta,Female,26,2023,MDI Gurgaon,B.Tech,Electronics & Communication,5.77,2,...,Lucknow,7/20/2021,Applied,NaN,35,NaN,110,60,NaN,No
8,9,Gargi Choudhury,Female,27,2023,NIT Calicut,MCA,Computer Applications,6.24,0,...,Mumbai,4/1/2024,HR Interview,4.0,4,NaN,1334,58,NaN,Yes
9,10,Jagdish Pandey,Male,20,2024,IIT Kanpur,BCA,Computer Applications,8.18,1,...,Mysuru,10/6/2022,Applied,NaN,26,NaN,586,97,NaN,No

In [11]:
freshers.index

RangeIndex(start=0, stop=5000, step=1)

In [12]:
# To check if there are any null values in the table
freshers.isnull()

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,job_location,application_date,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,True,False
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,True,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False

In [13]:
freshers.isnull().sum()

candidate_id                 0
full_name                    0
gender                       0
age                          0
graduation_year              0
college                      0
degree                       0
branch                       0
cgpa                         0
backlogs                     0
gap_year                     0
prior_internship             0
projects_count               0
certifications_count         0
top_skills                   0
platform                     0
company_applied              0
sector                       0
job_role                     0
work_type                    0
job_location                 0
application_date             0
hiring_stage                 0
interview_rounds          3182
response_time_days           0
offered_salary_inr        4378
linkedin_connections         0
profile_completion_pct       0
linkedin_premium          3901
referral_applied             0
dtype: int64

In [14]:
# To fill the null values with "Not available"
freshers = freshers.fillna("Not Available")

In [15]:
freshers.isnull().sum()

candidate_id              0
full_name                 0
gender                    0
age                       0
graduation_year           0
college                   0
degree                    0
branch                    0
cgpa                      0
backlogs                  0
gap_year                  0
prior_internship          0
projects_count            0
certifications_count      0
top_skills                0
platform                  0
company_applied           0
sector                    0
job_role                  0
work_type                 0
job_location              0
application_date          0
hiring_stage              0
interview_rounds          0
response_time_days        0
offered_salary_inr        0
linkedin_connections      0
profile_completion_pct    0
linkedin_premium          0
referral_applied          0
dtype: int64

In [16]:
# To check if there are any duplicate rows
freshers.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [17]:
freshers.duplicated().sum()

np.int64(0)

In [18]:
# To change the datatype of the column
freshers["application_date"] = pd.to_datetime(freshers["application_date"], errors = 'coerce')

In [19]:
# Removing the rows that are logically inconsistent
freshers["applied_year"] = freshers["application_date"].dt.year

In [20]:
freshers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   candidate_id            5000 non-null   int64
 1   full_name               5000 non-null   object
 2   gender                  5000 non-null   object
 3   age                     5000 non-null   int64
 4   graduation_year         5000 non-null   int64
 5   college                 5000 non-null   object
 6   degree                  5000 non-null   object
 7   branch                  5000 non-null   object
 8   cgpa                    5000 non-null   float64
 9   backlogs                5000 non-null   int64
 10  gap_year                5000 non-null   object
 11  prior_internship        5000 non-null   object
 12  projects_count          5000 non-null   int64
 13  certifications_count    5000 non-null   int64
 14  top_skills              5000 non-null   object
 15  platform                5000 non-null   object
 16  company_applied         5000 non-null   object
 17  sector                  5000 non-null   object
 18  job_role                5000 non-null   object
 19  work_type               5000 non-null   object
 20  job_location            5000 non-null   object
 21  application_date        5000 non-null   datetime64[ns]
 22  hiring_stage            5000 non-null   object
 23  interview_rounds        5000 non-null   object
 24  response_time_days      5000 non-null   int64
 25  offered_salary_inr      5000 non-null   object
 26  linkedin_connections    5000 non-null   int64
 27  profile_completion_pct  5000 non-null   int64
 28  linkedin_premium        5000 non-null   object
 29  referral_applied        5000 non-null   object
 30  applied_year            5000 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(1), int64(9), object(19)
memory usage: 1.2+ MB

In [21]:
freshers[freshers["applied_year"] < freshers["graduation_year"]]

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,application_date,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied,applied_year
1,2,Piyush Reddy,Male,25,2022,IIEST Shibpur,B.Sc (IT),Information Technology,8.78,0,...,2021-07-26,Shortlisted,Not Available,30,Not Available,2653,78,Yes,No,2021
2,3,Itisha Arora,Female,21,2024,BIT Mesra Ranchi,BCA,Computer Applications,6.24,3,...,2022-03-09,Rejected,4.0,37,Not Available,2990,75,Not Available,No,2022
7,8,Hema Sengupta,Female,26,2023,MDI Gurgaon,B.Tech,Electronics & Communication,5.77,2,...,2021-07-20,Applied,Not Available,35,Not Available,110,60,Not Available,No,2021
9,10,Jagdish Pandey,Male,20,2024,IIT Kanpur,BCA,Computer Applications,8.18,1,...,2022-10-06,Applied,Not Available,26,Not Available,586,97,Not Available,No,2022
11,12,Esha Jadhav,Female,24,2024,NIT Calicut,MBA,Marketing,8.59,2,...,2022-06-21,Applied,Not Available,29,Not Available,2309,100,Not Available,No,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4988,Tarun Dey,Male,20,2024,HBTU Kanpur,B.E.,Electronics,8.78,1,...,2022-09-29,Shortlisted,Not Available,43,Not Available,2094,96,Not Available,No,2022
4989,4990,Riddhi Lal,Female,22,2025,Lovely Professional University,B.Com,Accounting,5.76,0,...,2024-11-30,HR Interview,5.0,43,Not Available,1669,76,Not Available,No,2024
4990,4991,Lalit Pandey,Male,20,2025,IIM Calcutta,MBA,HR,6.46,1,...,2023-04-27,Applied,Not Available,1,Not Available,1718,75,Not Available,No,2023
4991,4992,Gargi Agarwal,Female,27,2025,Christ University Bangalore,MBA,Marketing,8.50,1,...,2022-04-16,Rejected,1.0,41,Not Available,559,81,Not Available,No,2022
4996,4997,Hemant Rajan,Male,24,2023,Osmania University Hyderabad,B.Tech,Computer Science,5.56,2,...,2021-04-16,Technical Interview,5.0,5,Not Available,1401,70,Yes,No,2021

In [22]:
freshers = freshers[freshers["applied_year"] >= freshers["graduation_year"]]

In [23]:
freshers.shape

(2907, 31)

In [24]:
# Adding new columns
freshers["skill_set_count"] = freshers["projects_count"] + freshers["certifications_count"]

In [25]:
freshers.head(5)

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied,applied_year,skill_set_count
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Technical Interview,3.0,22,Not Available,1188,64,Not Available,No,2021,5
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Online Assessment,Not Available,36,Not Available,97,98,No,No,2023,2
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Shortlisted,Not Available,2,Not Available,508,78,No,No,2024,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Shortlisted,Not Available,34,Not Available,1899,62,Not Available,No,2024,5
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Online Assessment,Not Available,31,Not Available,1717,67,Not Available,Yes,2024,8

In [26]:
freshers["career_gap"] = freshers["applied_year"] - freshers["graduation_year"]

In [27]:
freshers.head(10)

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied,applied_year,skill_set_count,career_gap
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,3.0,22,Not Available,1188,64,Not Available,No,2021,5,0
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Not Available,36,Not Available,97,98,No,No,2023,2,1
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Not Available,2,Not Available,508,78,No,No,2024,4,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Not Available,34,Not Available,1899,62,Not Available,No,2024,5,4
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Not Available,31,Not Available,1717,67,Not Available,Yes,2024,8,0
8,9,Gargi Choudhury,Female,27,2023,NIT Calicut,MCA,Computer Applications,6.24,0,...,4.0,4,Not Available,1334,58,Not Available,Yes,2024,9,1
10,11,Nikhil Patel,Male,27,2024,Symbiosis Pune,B.E.,Computer Science,7.92,2,...,Not Available,9,Not Available,1133,62,Not Available,No,2024,1,0
13,14,Ojaswini Chopra,Female,23,2022,NIT Trichy,B.E.,Civil,9.42,3,...,1.0,26,Not Available,2833,89,Not Available,No,2022,5,0
14,15,Abhinav Srivastava,Male,24,2020,IIT Hyderabad,BBA,HR,7.06,2,...,Not Available,28,Not Available,336,97,Not Available,No,2024,3,4
15,16,Charmi Malhotra,Female,24,2024,Delhi University,MCA,Computer Applications,7.31,2,...,5.0,30,Not Available,1859,83,Not Available,No,2024,8,0

In [28]:
freshers = freshers.drop("applied_year", axis=1)

In [29]:
freshers.head(10)

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied,skill_set_count,career_gap
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Technical Interview,3.0,22,Not Available,1188,64,Not Available,No,5,0
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Online Assessment,Not Available,36,Not Available,97,98,No,No,2,1
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Shortlisted,Not Available,2,Not Available,508,78,No,No,4,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Shortlisted,Not Available,34,Not Available,1899,62,Not Available,No,5,4
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Online Assessment,Not Available,31,Not Available,1717,67,Not Available,Yes,8,0
8,9,Gargi Choudhury,Female,27,2023,NIT Calicut,MCA,Computer Applications,6.24,0,...,HR Interview,4.0,4,Not Available,1334,58,Not Available,Yes,9,1
10,11,Nikhil Patel,Male,27,2024,Symbiosis Pune,B.E.,Computer Science,7.92,2,...,Applied,Not Available,9,Not Available,1133,62,Not Available,No,1,0
13,14,Ojaswini Chopra,Female,23,2022,NIT Trichy,B.E.,Civil,9.42,3,...,Technical Interview,1.0,26,Not Available,2833,89,Not Available,No,5,0
14,15,Abhinav Srivastava,Male,24,2020,IIT Hyderabad,BBA,HR,7.06,2,...,Applied,Not Available,28,Not Available,336,97,Not Available,No,3,4
15,16,Charmi Malhotra,Female,24,2024,Delhi University,MCA,Computer Applications,7.31,2,...,Technical Interview,5.0,30,Not Available,1859,83,Not Available,No,8,0

In [30]:
import numpy as np

In [31]:
# To find and remove outliers
a = freshers.sort_values("age")

q1 = np.percentile(a["age"],25)
q2 = np.percentile(a["age"],50)
q3 = np.percentile(a["age"],75)

print(f"q1 = {q1}")
print(f"q2 = {q2}")
print(f"q3 = {q3}")

iqr = q3 -q1
print(f"iqr = {iqr}")

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
print(f"lower = {lower}")
print(f"upper = {upper}")

outliers = freshers[(freshers["age"] <= lower) | (freshers["age"] >= upper)]
print(outliers)

q1 = 22.0
q2 = 23.0
q3 = 25.0
iqr = 3.0
lower = 17.5
upper = 29.5
Empty DataFrame
Columns: [candidate_id, full_name, gender, age, graduation_year, college, degree, branch, cgpa, backlogs, gap_year, prior_internship, projects_count, certifications_count, top_skills, platform, company_applied, sector, job_role, work_type, job_location, application_date, hiring_stage, interview_rounds, response_time_days, offered_salary_inr, linkedin_connections, profile_completion_pct, linkedin_premium, referral_applied, skill_set_count, career_gap]
Index: []

[0 rows x 32 columns]

In [32]:
# Trimming Extra Spaces
text_columns = freshers.select_dtypes(include = ["object"]).columns
print(text_columns)

for c in text_columns:
    freshers[c] = freshers[c].astype(str).str.strip()

Index(['full_name', 'gender', 'college', 'degree', 'branch', 'gap_year',
       'prior_internship', 'top_skills', 'platform', 'company_applied',
       'sector', 'job_role', 'work_type', 'job_location', 'hiring_stage',
       'interview_rounds', 'offered_salary_inr', 'linkedin_premium',
       'referral_applied'],
      dtype='object')

In [33]:
freshers

,candidate_id,full_name,gender,age,graduation_year,college,degree,branch,cgpa,backlogs,...,hiring_stage,interview_rounds,response_time_days,offered_salary_inr,linkedin_connections,profile_completion_pct,linkedin_premium,referral_applied,skill_set_count,career_gap
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Technical Interview,3.0,22,Not Available,1188,64,Not Available,No,5,0
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Online Assessment,Not Available,36,Not Available,97,98,No,No,2,1
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Shortlisted,Not Available,2,Not Available,508,78,No,No,4,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Shortlisted,Not Available,34,Not Available,1899,62,Not Available,No,5,4
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Online Assessment,Not Available,31,Not Available,1717,67,Not Available,Yes,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,4995,Meera Anand,Female,26,2021,JNTUH Hyderabad,MBA,Strategy,8.03,1,...,Applied,Not Available,5,Not Available,458,76,Not Available,No,6,1
4995,4996,Bhumi Shukla,Female,20,2021,IIM Calcutta,B.Sc (CS),Computer Science,7.94,1,...,Technical Interview,5.0,40,Not Available,1392,84,Not Available,Yes,5,2
4997,4998,Ojaswi More,Female,21,2020,NIT Calicut,BBA,Marketing,9.71,1,...,Applied,Not Available,12,Not Available,1159,66,Not Available,No,4,3
4998,4999,Ojaswi Kumar,Female,23,2021,Pune University,M.Tech,VLSI,6.84,1,...,Applied,Not Available,21,Not Available,399,84,Not Available,Yes,2,3
4999,5000,Shivam Sharma,Male,25,2020,Jadavpur University Kolkata,MBA,Operations,7.20,0,...,Technical Interview,3.0,14,Not Available,2586,87,Not Available,Yes,5,2

In [34]:
freshers.columns = freshers.columns.str.strip().str.title()

In [35]:
# Renaming the columns
freshers = freshers.rename(columns = {"Cgpa" : "CGPA", "Platform" : "Job_Application_Platform"})

In [36]:
freshers

,Candidate_Id,Full_Name,Gender,Age,Graduation_Year,College,Degree,Branch,CGPA,Backlogs,...,Hiring_Stage,Interview_Rounds,Response_Time_Days,Offered_Salary_Inr,Linkedin_Connections,Profile_Completion_Pct,Linkedin_Premium,Referral_Applied,Skill_Set_Count,Career_Gap
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Technical Interview,3.0,22,Not Available,1188,64,Not Available,No,5,0
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Online Assessment,Not Available,36,Not Available,97,98,No,No,2,1
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Shortlisted,Not Available,2,Not Available,508,78,No,No,4,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Shortlisted,Not Available,34,Not Available,1899,62,Not Available,No,5,4
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Online Assessment,Not Available,31,Not Available,1717,67,Not Available,Yes,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,4995,Meera Anand,Female,26,2021,JNTUH Hyderabad,MBA,Strategy,8.03,1,...,Applied,Not Available,5,Not Available,458,76,Not Available,No,6,1
4995,4996,Bhumi Shukla,Female,20,2021,IIM Calcutta,B.Sc (CS),Computer Science,7.94,1,...,Technical Interview,5.0,40,Not Available,1392,84,Not Available,Yes,5,2
4997,4998,Ojaswi More,Female,21,2020,NIT Calicut,BBA,Marketing,9.71,1,...,Applied,Not Available,12,Not Available,1159,66,Not Available,No,4,3
4998,4999,Ojaswi Kumar,Female,23,2021,Pune University,M.Tech,VLSI,6.84,1,...,Applied,Not Available,21,Not Available,399,84,Not Available,Yes,2,3
4999,5000,Shivam Sharma,Male,25,2020,Jadavpur University Kolkata,MBA,Operations,7.20,0,...,Technical Interview,3.0,14,Not Available,2586,87,Not Available,Yes,5,2

In [37]:
# Two sample t-test
# To check whether the candidates who were hired and not hired have difference in the their projects count or not.
# (ie., to check whether the candidates are hired based on project count)

Hired = freshers[freshers["Hiring_Stage"] == "Offer"]["Projects_Count"]
Not_Hired = freshers[freshers["Hiring_Stage"] != "Offer"]["Projects_Count"]

print(f"Average project count of candidates who are hired : {Hired.mean()}")
print(f"Average project count of candidates who are not hired : {Not_Hired.mean()}")

from scipy.stats import ttest_ind

# H0 : There is no difference between the avrage projects count of candidates who are hired and not hired
# H1 : There is a significant difference between the average project count of candidates who are hired and not hired

t_statistic, p_value = ttest_ind(Hired, Not_Hired)
print(f"t_statistic : {t_statistic}")
print(f"p-value : {p_value}")

alpha = 0.05

if p_value < alpha:
    print("Reject H0, there is a differnce between the project count of candidates who are hired and not hired")
else:
    print("Failed to reject H0, There is no difference between the project count of candidates who are hired and not hired")

# so, companies didnt hire candidates only based on project count. Other factors may also influence the hiring outcome

Average project count of candidates who are hired : 3.0
Average project count of candidates who are not hired : 2.980171073094868
t_statistic : 0.1707034013129032
p-value : 0.8644688760877566
Failed to reject H0, There is no difference between the project count of candidates who are hired and not hired

In [38]:
# Correlation
# To check whether the candidates with high CGPA gets high salary

CGPA_of_hired_candidates = freshers[freshers["Hiring_Stage"] == "Offer"]["CGPA"]
Salary = freshers[freshers["Hiring_Stage"] == "Offer"]["Offered_Salary_Inr"]

print(CGPA_of_hired_candidates)
print(Salary)

Salary = Salary.astype(float)
print(type(Salary))

from scipy import stats

#H0 : There is no relationship between CGPA and salary of the candidates
#H1 : There is a relationship between CGPA and salary of the candidates.

correlation, p_value = stats.pearsonr(CGPA_of_hired_candidates, Salary)
print(f"Correlation : {correlation}")
print(f"p-value : {p_value}")

#Correlation
if correlation > 0:
    print("There is a positive relationship")
elif correlation == 0:
    print("There is no relationship")
else:
    print("There is a negative relationship")

#P-value
alpha = 0.05

if p_value < alpha:
    print("Reject H0, There is a relationship between CGPA and salary of the candidates")
else:
    print("Failed to reject H0, There is no relationship between CGPA and salary of the candidates")
# There is a negatve relationship, so candidates with high salary gets low salary or the candidates with low salary gets high salary.
# But the relationship is very weak, so CGPA alone is not the reason for their high or low salary, Other factors may also influence the salary.

21      9.84
25      6.73
81      8.42
98      9.97
110     6.11
        ...
4926    7.19
4963    7.46
4972    5.96
4976    8.53
4992    9.32
Name: CGPA, Length: 335, dtype: float64
21        34090.0
25       720172.0
81       403011.0
98       347616.0
110     1130729.0
          ...
4926     481333.0
4963     848283.0
4972     584467.0
4976    1040093.0
4992     387946.0
Name: Offered_Salary_Inr, Length: 335, dtype: object
<class 'pandas.core.series.Series'>
Correlation : -0.12705005343902825
p-value : 0.020011088099109946
There is a negative relationship
Reject H0, There is a relationship between CGPA and salary of the candidates

In [39]:
# Probability 
# If I choose one candidate at random, what is the probability of choosing a candidate who has reference?

Reference = len(freshers[freshers["Referral_Applied"] == "Yes"])
print(Reference)
Total_candidates = len(freshers)
print(Total_candidates)

probability = Reference /Total_candidates
print(f"the probability of choosing a candidate who has reference is {round(probability * 100,2)}%")

458
2907
the probability of choosing a candidate who has reference is 15.76%

In [40]:
# Descriptive statistics
columns = ["Age", "CGPA", "Backlogs", "Projects_Count", "Certifications_Count", "Response_Time_Days", "Profile_Completion_Pct"]
for s in columns:
    print(s)
    print(f"Mean = {freshers[s].mean()}")
    print(f"Median = {freshers[s].median()}")
    print(f"Mode = {freshers[s].mode()[0]}")
    print(f"Variance = {freshers[s].var()}")
    print(f"Standard Deviation = {freshers[s].std()}")

Age
Mean = 23.466460268317853
Median = 23.0
Mode = 24
Variance = 5.164996516228927
Standard Deviation = 2.272662869021476
CGPA
Mean = 7.7317991056071556
Median = 7.72
Mode = 5.8
Variance = 1.7232301069090428
Standard Deviation = 1.3127185939526578
Backlogs
Mean = 1.520811833505332
Median = 2.0
Mode = 2
Variance = 1.2448351287243729
Standard Deviation = 1.1157217971897713
Projects_Count
Mean = 2.982456140350877
Median = 3.0
Mode = 4
Variance = 3.997971528960056
Standard Deviation = 1.9994928179316014
Certifications_Count
Mean = 2.498108015135879
Median = 3.0
Mode = 3
Variance = 2.881190500372806
Standard Deviation = 1.6974069931436027
Response_Time_Days
Mean = 23.309941520467838
Median = 24.0
Mode = 24
Variance = 166.75145997593228
Standard Deviation = 12.913228100515079
Profile_Completion_Pct
Mean = 77.76814585483316
Median = 78.0
Mode = 83
Variance = 172.41284594155493
Standard Deviation = 13.13060721907235

In [41]:
freshers

,Candidate_Id,Full_Name,Gender,Age,Graduation_Year,College,Degree,Branch,CGPA,Backlogs,...,Hiring_Stage,Interview_Rounds,Response_Time_Days,Offered_Salary_Inr,Linkedin_Connections,Profile_Completion_Pct,Linkedin_Premium,Referral_Applied,Skill_Set_Count,Career_Gap
0,1,Deepika Shukla,Female,23,2021,BITS Goa,B.E.,Electrical,5.89,3,...,Technical Interview,3.0,22,Not Available,1188,64,Not Available,No,5,0
3,4,Darshan Dey,Male,22,2022,BITS Goa,B.Sc (CS),Computer Science,8.86,3,...,Online Assessment,Not Available,36,Not Available,97,98,No,No,2,1
4,5,Uma Grewal,Female,25,2020,Pune University,MCA,Computer Applications,7.54,2,...,Shortlisted,Not Available,2,Not Available,508,78,No,No,4,4
5,6,Siddharth Kulkarni,Male,21,2020,Osmania University Hyderabad,M.Tech,Computer Science,9.90,1,...,Shortlisted,Not Available,34,Not Available,1899,62,Not Available,No,5,4
6,7,Rohan Bhatt,Male,23,2024,VIT Vellore,B.Tech,Electronics & Communication,8.69,0,...,Online Assessment,Not Available,31,Not Available,1717,67,Not Available,Yes,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,4995,Meera Anand,Female,26,2021,JNTUH Hyderabad,MBA,Strategy,8.03,1,...,Applied,Not Available,5,Not Available,458,76,Not Available,No,6,1
4995,4996,Bhumi Shukla,Female,20,2021,IIM Calcutta,B.Sc (CS),Computer Science,7.94,1,...,Technical Interview,5.0,40,Not Available,1392,84,Not Available,Yes,5,2
4997,4998,Ojaswi More,Female,21,2020,NIT Calicut,BBA,Marketing,9.71,1,...,Applied,Not Available,12,Not Available,1159,66,Not Available,No,4,3
4998,4999,Ojaswi Kumar,Female,23,2021,Pune University,M.Tech,VLSI,6.84,1,...,Applied,Not Available,21,Not Available,399,84,Not Available,Yes,2,3
4999,5000,Shivam Sharma,Male,25,2020,Jadavpur University Kolkata,MBA,Operations,7.20,0,...,Technical Interview,3.0,14,Not Available,2586,87,Not Available,Yes,5,2

In [42]:
freshers.to_csv("freshers_hiring_india_dataset.csv",index = False)